s=str(input("nhập chuỗi s: "))
s_sub=str(input("Nhập chuỗi con: "))
s_find=str(input("nhập chuỗi tìm: "))
s_replace=input("nhập chuỗi thay thế: ")
s=s.replace(s_find,s_replace)
s=s.strip()
print("chuỗi sau khi loại bỏ khoảng trắng ở đầu và cuối",s)
print("số lần s_sub xuất hiện trong s",s.count(s_sub))
s=s.capitalize()
print("chuỗi s sau khi tìm kiếm và thay thế",s)

