s=str(input("nhập chuỗi s: "))
s_sub=str(input("Nhập chuỗi con: "))
s_find=str(input("nhập chuỗi tìm: "))
s_replace=input("nhập chuỗi thay thế: ")
b=s.find(s_find)
s=s.replace(s_find,s_replace)
s=s.strip()
print("chuỗi sau khi loại bỏ khoảng trắng ở đầu và cuối",s)
print("số lần s_sub xuất hiện tron s",s.count(s_sub))
s=s.capitalize()
print(s)

